### Lire toutes les ressources de la collection
GET http://localhost:3000/films

### Lire toutes les ressources de la collection avec un filtre
GET http://localhost:3000/films?minimum-duration=150

### Lire une ressource identifiée
GET http://localhost:3000/films/1

### Créer une ressource
POST http://localhost:3000/films
Content-Type: application/json

{
    "title": "The Dark Knight",
    "director": "Christopher Nolan",
    "duration": 152,
    "budget": 185,
    "description": "A superhero film",
    "imageUrl": "https://example.com/darkknight.jpg"
}
